### ISSUE TITLE
Horse Don't Appear

### ISSUE THREAD

**Issue by Smidds** [AddstarMC/NaturalHorses#5]
I have the chat debugging on (Horse's location is given) and i'm riding another horse around to find them, but they don't appear. Only once i've teleported to the horse's xyz, only then do they show. Also, i'll be looking for horses, it'll give me the area, and once i've teleported to it, i'll find out that it was actually right next to me, i just couldn't see the horses.

Another comment, are wild horses supposed to despawn? Because wild horses do, but not tamed ones

**Comment by addstar** [comment]
Hello,
There have been many issues in the previous builds but all these issues (and many more) should be resolved in 1.0.5, which is currently awaiting Bukkit approval.
